# Generated by Django 4.2.11 on 2024-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=225)),
                ('date_2012', models.CharField(max_length=150)),
                ('date_2022', models.CharField(max_length=150)),
            ],
        ),
    ]
